name: tests

on: [push, pull_request]

jobs:
    tests:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                swift: ["5.7", "5.8"]
                include:
                    - os: macos-11
                      swift: 4.2
                    - os: ubuntu-20.04
                      swift: 4.2
                    - os: ubuntu-20.04
                      swift: 5.6
                    - os: macos-latest
                      swift: 5.6
        runs-on: ${{ matrix.os }}
        steps:
            - uses: swift-actions/setup-swift@v1
              with:
                  swift-version: ${{ matrix.swift }}
            - uses: actions/checkout@v3
            - name: build
              run: swift build
            - name: test
              run: swift test
