name: tests

on: [push, pull_request]

jobs:
    tests:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                swift: ["4.0", "4.2", "5.7", "5.8"]
                include:
                    - os: [ubuntu-20.04, macos-latest]
                      swift: 5.6
        runs-on: ${{ matrix.os }}
        steps:
            - uses: swift-actions/setup-swift@v1
              with:
                  swift-version: ${{ matrix.swift }}
            - uses: actions/checkout@v3
            - name: build
              run: swift build
            - name: test
              run: swift test
